### ISSUE TITLE
New release to fix startup prompts?

### ISSUE THREAD

**Issue by shian48263** [mdegoo/sublime-bootstrap4#9]
After merging PR #8, I think a new release should be issued to fix the startup errors prompt.

Maybe 0.1.2.1? Else those prompts will still show up every time Sublime Text is launched.

Thanks.

**Comment by mdegoo** [comment]
Fixed.

Can you give me feedback?

**Comment by shian48263** [comment]
With Package Control, no package is updated.

While after I remove this package and reinstall it again, it's still the same.

**Comment by mdegoo** [comment]
We have to wait Package Control next checking

**Comment by mdegoo** [comment]
All others packages have the same "Last Seen". Must be a PC bug...

Please try the Github install method

**Comment by shian48263** [comment]
Is there any bug report on that?

**Comment by mdegoo** [comment]
Apparently no, and there is no new packages yet since 4 days.

**Comment by equinusocio** [comment]
Link to the issue wbond/package_control_channel#5283.

**Comment by mdegoo** [comment]
Thanks @equinusocio !! :+1: 

Please use option 2 or 3 to fix the current state problem :
https://github.com/mdegoo/sublime-bootstrap4#install

**Comment by shian48263** [comment]
Resolved by [wbond](https://github.com/wbond/package_control/issues/1090#event-571877002)
